# -*- coding: utf-8 -*-
"""stock_ranker

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12IlySZm9rrWl2nAV91FKJCDxivcABZ9g
"""

# -*- coding: utf-8 -*-
"""
MFT105 期末专案：股票筛选与排名器（模型类 + OOS 验证）
小组成员：张晨煦，王滢
"""
import yfinance as yf
import pandas as pd
import numpy as np
from datetime import datetime, timedelta

# ===================== 股票池 =====================
tickers = [
    "AAPL", "MSFT", "GOOGL", "AMZN", "JPM", "V", "KO", "PG", "WMT", "JNJ",
    "600519.SS", "600036.SS", "300750.SZ",
    "0700.HK", "0005.HK"
]

# ===================== 核心参数（OOS 用） =====================
TRAIN_DAYS = 180  # 训练集天数
OOS_DAYS = 60     # 样本外天数

# ===================== 数据获取（支持时间区间） =====================
def fetch_stock_data_period(tickers, start_date, end_date):
    stock_data = []
    for ticker in tickers:
        try:
            stock = yf.Ticker(ticker)
            info = stock.info
            hist = stock.history(start=start_date, end=end_date)
            if hist.empty:
                continue
            close_prices = hist["Close"]
            # 基础指标
            pe_ratio = info.get("trailingPE", np.nan)
            pb_ratio = info.get("priceToBook", np.nan)
            roe = info.get("returnOnEquity", np.nan)
            debt_ratio = info.get("debtToEquity", np.nan)
            dividend_yield = info.get("dividendYield", 0)
            # 收益与波动
            period_return = (close_prices.iloc[-1] / close_prices.iloc[0]) - 1
            volatility = close_prices.pct_change().std() * np.sqrt(252)

            stock_data.append({
                "代码": ticker,
                "名称": info.get("longName", ticker),
                "市盈率(PE)": pe_ratio,
                "市净率(PB)": pb_ratio,
                "净资产收益率(ROE)": roe,
                "资产负债率(%)": debt_ratio,
                "期间收益率": period_return,
                "年化波动率": volatility,
                "股息率": dividend_yield
            })
        except Exception as e:
            continue
    return pd.DataFrame(stock_data)

# ===================== 评分模型 =====================
def calculate_scores(df):
    df_scored = df.copy().dropna()
    # 估值：PE、PB 越低分越高
    df_scored["估值得分"] = (df_scored["市盈率(PE)"].rank(ascending=False) +
                            df_scored["市净率(PB)"].rank(ascending=False)) / 2
    # 品质：ROE 越高、负债率越低分越高
    df_scored["品质得分"] = (df_scored["净资产收益率(ROE)"].rank(ascending=True) +
                            df_scored["资产负债率(%)"].rank(ascending=False)) / 2
    # 动能：收益越高分越高
    df_scored["动能得分"] = df_scored["期间收益率"].rank(ascending=True)
    # 风险：波动越低分越高
    df_scored["风险得分"] = df_scored["年化波动率"].rank(ascending=False)

    # 归一化到 0-10
    for col in ["估值得分", "品质得分", "动能得分", "风险得分"]:
        df_scored[col] = (df_scored[col] / df_scored[col].max()) * 10

    # 综合得分
    df_scored["综合得分"] = (df_scored["估值得分"] + df_scored["品质得分"] +
                            df_scored["动能得分"] + df_scored["风险得分"]) / 4
    df_scored = df_scored.sort_values("综合得分", ascending=False)
    df_scored["排名"] = range(1, len(df_scored) + 1)
    return df_scored

# ===================== 选股理由 =====================
def generate_reason(row):
    reasons = []
    if row["估值得分"] >= 8:
        reasons.append("估值极具吸引力")
    elif row["估值得分"] >= 6:
        reasons.append("估值合理")
    if row["品质得分"] >= 8:
        reasons.append("财务状况非常健康")
    elif row["品质得分"] >= 6:
        reasons.append("财务状况良好")
    if row["动能得分"] >= 8:
        reasons.append("近期走势强劲")
    elif row["动能得分"] >= 6:
        reasons.append("近期走势稳健")
    if row["风险得分"] >= 8:
        reasons.append("风险极低")
    elif row["风险得分"] >= 6:
        reasons.append("风险可控")
    if not reasons:
        reasons.append("指标均衡")
    return "; ".join(reasons)

# ===================== 风险警示 =====================
def risk_warning(row):
    warn = []
    if row["年化波动率"] > 0.35:
        warn.append("⚠️ 高波动风险")
    if row["市盈率(PE)"] > 30:
        warn.append("⚠️ 估值偏高")
    if row["净资产收益率(ROE)"] < 0.1:
        warn.append("⚠️ 盈利偏弱")
    return " ".join(warn)

# ===================== OOS 样本外验证（核心新增） =====================
def oos_validation(tickers):
    print("\n" + "="*88)
    print("                         OOS 样本外验证开始")
    print("="*88)

    # 1. 计算时间区间
    end_date = datetime.today()
    oos_start = end_date - timedelta(days=OOS_DAYS)
    train_start = oos_start - timedelta(days=TRAIN_DAYS)

    # 修复：train_date → train_start
    print(f"训练区间：{train_start.strftime('%Y-%m-%d')} ~ {oos_start.strftime('%Y-%m-%d')}")
    print(f"OOS 验证区间：{oos_start.strftime('%Y-%m-%d')} ~ {end_date.strftime('%Y-%m-%d')}")

    # 2. 训练集：建模
    df_train = fetch_stock_data_period(tickers, train_start, oos_start)
    if df_train.empty:
        print("训练集数据不足")
        return None
    df_train_scored = calculate_scores(df_train)
    top3_train = df_train_scored.head(3)["代码"].tolist()

    # 3. OOS 测试集：只看未来收益，不参与建模
    df_oos = fetch_stock_data_period(tickers, oos_start, end_date)
    if df_oos.empty:
        print("OOS 数据不足")
        return None

    # 4. OOS 收益统计
    oos_return_all = df_oos["期间收益率"].mean()
    top3_oos = df_oos[df_oos["代码"].isin(top3_train)]
    if len(top3_oos) < 1:
        print("OOS 无 Top3 数据")
        return None

    oos_return_top3 = top3_oos["期间收益率"].mean()
    oos_excess = oos_return_top3 - oos_return_all
    oos_win_rate = len(top3_oos[top3_oos["期间收益率"] > oos_return_all]) / len(top3_oos)

    # 5. 输出 OOS 验证结果
    print("\n【OOS 验证结果】")
    print(f"股票池 OOS 平均收益：{oos_return_all:.2%}")
    print(f"模型 Top3 OOS 收益：{oos_return_top3:.2%}")
    print(f"OOS 超额收益：{oos_excess:.2%}")
    print(f"OOS 胜率（跑赢平均）：{oos_win_rate:.2%}")
    print("="*88)

    return {
        "oos_return_all": oos_return_all,
        "oos_return_top3": oos_return_top3,
        "oos_excess": oos_excess,
        "oos_win_rate": oos_win_rate,
        "top3_codes": top3_train
    }

# ===================== 主程序 =====================
if __name__ == "__main__":
    print("="*88)
    print("               MFT105 期末专案：股票筛选与排名器（模型类）")
    print("="*88)

    # 1. 全样本正常输出
    print("\n正在获取全样本数据...")
    end_all = datetime.today()
    start_all = end_all - timedelta(days=365)
    df_stocks = fetch_stock_data_period(tickers, start_all, end_all)

    if not df_stocks.empty:
        print("正在计算综合得分...")
        df_result = calculate_scores(df_stocks)
        df_result["选股理由"] = df_result.apply(generate_reason, axis=1)
        df_result["风险警示"] = df_result.apply(risk_warning, axis=1)

        final_columns = ["排名","代码","名称","综合得分","市盈率(PE)","净资产收益率(ROE)","期间收益率","年化波动率","选股理由","风险警示"]
        df_final = df_result[final_columns].round(2)

        print("\n【全样本筛选结果】")
        print("-" * 120)
        print(f"{'排名':<4}{'代码':<12}{'名称':<26}{'综合得分':<10}{'PE':<10}{'ROE':<10}{'收益率':<10}{'波动率':<10}{'选股理由':<24}{'风险警示':<12}")
        print("-" * 120)
        for _, r in df_final.iterrows():
            print(f"{r['排名']:<4}{r['代码']:<12}{r['名称'][:24]:<26}{r['综合得分']:<10}{r['市盈率(PE)']:<10}{r['净资产收益率(ROE)']:<10}{r['期间收益率']:<10.2%}{r['年化波动率']:<10.2f}{r['选股理由']:<24}{r['风险警示']:<12}")
        print("-" * 120)

        # 全样本基准对照
        bench_ret = df_stocks["期间收益率"].mean()
        top3_ret = df_result.head(3)["期间收益率"].mean()
        print("\n【全样本基准对照】")
        print(f"股票池平均收益率: {bench_ret:.2%}")
        print(f"排名前三平均收益率: {top3_ret:.2%}")
        print(f"模型相对基准增益: {top3_ret - bench_ret:.2%}")

    # 2. OOS 验证（独立验证机制）
    oos_result = oos_validation(tickers)
# ===================== 可视化模块（绝对不报错版）=====================
import matplotlib.pyplot as plt
import seaborn as sns
from math import pi

# 字体设置
plt.rcParams["font.sans-serif"] = ["DejaVu Sans"]
plt.rcParams["axes.unicode_minus"] = False

# -------------------- 1. 综合得分排名柱状图 --------------------
plt.figure(figsize=(12, 5))
sns.barplot(data=df_final, x="名称", y="综合得分", palette="viridis")
plt.title("Stock Comprehensive Score Ranking", fontsize=14, fontweight='bold')
plt.xlabel("Stock Name", fontsize=12)
plt.ylabel("Composite Score", fontsize=12)
plt.xticks(rotation=45, ha="right")
plt.tight_layout()
plt.show()

# -------------------- 2. 收益率 vs 波动率 散点图 --------------------
plt.figure(figsize=(10, 5))
sns.scatterplot(data=df_final, x="年化波动率", y="期间收益率", hue="名称", s=100)
plt.title("Return vs Volatility", fontsize=14, fontweight='bold')
plt.xlabel("Annualized Volatility", fontsize=12)
plt.ylabel("Return", fontsize=12)
plt.grid(alpha=0.3)
plt.tight_layout()
plt.show()

# -------------------- 3. 第一名股票 四维得分雷达图 --------------------
def plot_radar(row):
    categories = ["Valuation", "Quality", "Momentum", "Risk"]
    values = [row["估值得分"], row["品质得分"], row["动能得分"], row["风险得分"]]
    values += values[:1]
    
    angles = [n / float(len(categories)) * 2 * pi for n in range(len(categories))]
    angles += angles[:1]
    
    plt.figure(figsize=(6, 6))
    ax = plt.subplot(111, polar=True)
    
    ax.plot(angles, values, 'o-', linewidth=2, label=row["名称"])
    ax.fill(angles, values, alpha=0.25)
    
    ax.set_xticks(angles[:-1])
    ax.set_xticklabels(categories, fontsize=12)
    plt.title(f"Top {row['排名']} Stock: {row['名称']} - 4-Dim Score", 
              fontsize=14, fontweight='bold', pad=20)
    plt.legend(loc='upper right', bbox_to_anchor=(1.2, 1.1))
    plt.tight_layout()
    plt.show()

plot_radar(df_result.iloc[0])

# -------------------- 4. OOS 收益对比图 --------------------
if oos_result is not None:
    labels = ["Stock Pool Avg", "Model Top3"]
    values = [oos_result["oos_return_all"], oos_result["oos_return_top3"]]
    
    plt.figure(figsize=(6, 4))
    sns.barplot(x=labels, y=values, palette=["gray", "orange"])
    plt.title("OOS Return Comparison", fontsize=14, fontweight='bold')
    plt.xlabel("Group", fontsize=12)
    plt.ylabel("Return", fontsize=12)
    plt.tight_layout()
    plt.show()
